version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,https://jobsweep-ui.vercel.app,http://jobsweep-ui.vercel.app
      - CORS_ALLOW_CREDENTIALS=true
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - jobsweep-network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - jobsweep-network

  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOSTS=redis:redis:6379:0,redis:redis:6379:1,redis:redis:6379:2
    depends_on:
      - redis
    networks:
      - jobsweep-network

  celery-worker:
    build: .
    command: celery -A services.celery_worker worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
    networks:
      - jobsweep-network

  celery-beat:
    build: .
    command: celery -A services.celery_app.celery beat -S redbeat.RedBeatScheduler
    volumes:
      - .:/app
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
      - celery-worker
    networks:
      - jobsweep-network

networks:
  jobsweep-network:
    driver: bridge

volumes:
  redis_data:

